### PR TITLE
Add form extension fixer (getExtendedType)

### LINKED ISSUE #29: [2.8] FormExtensionFixer
Hey,

another one very similar to the `FormTypeFixer`. Upgrading form type extensions:

Before:

``` php
class MyTypeExtension extends AbstractTypeExtension
{
   public function getExtendedType()
   {
       return 'form';
   }
}
```

After:

``` php
use Symfony\Component\Form\Extension\Core\Type\FormType;

class MyTypeExtension extends AbstractTypeExtension
{
   public function getExtendedType()
   {
       return FormType::class;
   }
}
```

Cheers
Matthias

### PR DESCRIPTION
**Pull request by aivus**
closes #29

### CODE REVIEW

**Comment by aivus** [comment]
Failed test will be fixed after #37

**Comment by TomasVotruba** [comment]
@aivus Thanks for your work, I could easily understand your code.
I've included this fix in https://github.com/RectorPHP/Rector/pull/104, in case you'd still need it.

**Comment by TomasVotruba** [comment]
It's related only to HHVM and no-support on PHPUnit 6.0 - see Travis: https://travis-ci.org/umpirsky/Symfony-Upgrade-Fixer/jobs/290471641#L637

image


Since Symfony isn't supporting either, I recommend dropping it off.

**Comment by aivus** [comment]
It was fixed in master and tests will be green after backmerge. I'll do it
soon.

**Comment by aivus** [comment]
@umpirsky tests are green

**Comment by umpirsky** [comment]
Thanks!

**Pull request merged**
